version: "3"
services:
  backend:
    # command: npm run db:migrate && npm run start
    command:
      [
        "sh",
        "-c",
        "npm install && npm run db:generate && npm run db:migrate && npm start",
      ]
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydatabase
      DATABASE_URL: postgres://user:password@db:5432/mydatabase

  frontend:
    command: ["sh", "-c", "npm install && npm start"]
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    # environment:
    #   CHOKIDAR_USEPOLLING: "true"
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  postgres_data:
